name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.6.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f132821afa1b198e879af59a5dbe0ba28e8b924a83ec0e616457e73f83ada505"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
