name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3569ec10bb4a4484638d6698e33c7174818338248d52df91049ed3ff52b27191"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
