name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.17.15"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20c3ad98eaef8c9262387c3e816e65900dea8780bad277cd22c29affb6ad3a07"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
