name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.14.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d114d944a1421537c39ef319b4559a18bebb678f8387d1d3c768e61083940d85"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
