name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.9.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cab167a5f6756101ee5dd464f353c8cc62e789b4484030b00c85ab6edde32389"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
