name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.16.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "139ab04f89b7c7a4498ad92eb5e32ae99d3e0d2292ee57593064547a00797075"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
