name = "Pepsi Dogs"
author = "Dan Porter"
version = "2.13.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04c249b8575dac77827977bcf7d7acb1c07f7423a86314c0fb2e8de496eb8b5c"

[versions]
fabric = "0.12.11"
minecraft = "1.18"
