name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.10.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0217884397de19682d8155d1cb18c2c3f4bef9bd0a510d080fa8a8d846bcd26"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
