name = "Pepsi Dogs"
author = "Dan Porter"
version = "2.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "971450f1370e3bb63498478134bb1cc74c6ccd1f37034ab38cc646bbe1c03aaf"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
