name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.17.13"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f317f947bff3f3c93b5ff637c4e4439f7ec970b9fe6c83687748e98884ef6a3d"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
