name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.9.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c55e0b2da9e267b96d08373399aa6be905ec23af0c736c0cafb3b5b5adef3ee"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
