name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.16.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3c94afcd27650eaf4e8d98f49232c50178517037d6ba907f58043a2e62fa5ba"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
