name = "Pepsi Dogs"
author = "Dan Porter"
version = "2.11.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9727935270053cee4908d9d5dfb4c85777c65ca341dd798dfc1c9ce5e8f3910e"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
