name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.10.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d686352827f9fc3391a6ee9a8eafed91d9aa9cc128f965e8d454a5d55e8aecf"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
