name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.10.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a85323edd12fe9cf070922ea9c633d7e7e1f369b59af3d7436a14040c453fe7"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
