name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.10.7"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d87d799945e9c62085f174645f4518de71ca84ef510a4ec2d2889eabd51c473"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
