name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.10.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7a4a7228b7500ee76149d5d124d324ee4876aea45ac6775a858aae301442f69"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
