name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.16.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c65b0c2947f0dad826465f77e754303ee0789d407f3b9abe1958e107c5650c4e"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
