name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.3.7"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81084042c3ee9e653bd9f918cfc5727f2b53a8b557854734ac2f7df99b4e3cf6"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
