name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.13.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d2a562ca7a10908ab1a0273484992199915e8bfe7c264323bb8251d501e47c2"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
