name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.17.24"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1fc494a77b70294d12eacfa7be1d20904c83f476efcaa2f91a3b026998da70b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
