name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.19.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2169fffb0b68d8e4d2ac0c0f59a16c0a58f653b078b004b9d37baf6820acf4e"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
