name = "Pepsi Dogs"
author = "Dan Porter"
version = "2.13.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37ff2f45ed4c67727ec896ad64b3962ef885f6ad41c5d47b9c94a948b6036e30"

[versions]
fabric = "0.12.9"
minecraft = "1.18"
