name = "Pepsi Dogs"
author = "Dan Porter"
version = "2.13.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97273e2962cc495a6d0b6ef6a83414dea87a4cd77788c95d6e4771e6796b78bf"

[versions]
fabric = "0.12.9"
minecraft = "1.18"
