name = "Pepsi Dogs"
author = "Dan Porter"
version = "2.7.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66c22cfbb6ddd2d2ee9f71534fd976a3bdd150a081256f90f540604fea8009fd"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
