name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.10.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfb2a6301196e2e0c576beba53cf3859f590f153af3a9cf3c29b3222b467444f"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
