name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.12.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c585bb5a2c750f396a15a02805059eda764983e199a876d4b71c88221ff976c"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
