name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.7.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c15147adfdf11c4a22cda7bea38dfa9d3af7386bd259273337063102f3f0058"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
