name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.3.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3f6e0341028f3a2d1b5962aa5f1466e44d6e98f7bb04abe8f0b91392764ca52"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
