name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.14.7"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e514ad6f20f56ea6919ee800329c829ebc3863b37fa02044960349b1d02234e2"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
