name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.14.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49363049bcfe23cd3ef6da2c04912cee99e0bb32326dc19a1cf113f2c62bf227"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
