name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.6.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f39fa029a935da91e72f1083d4847227d2efb41192632905a423b28f95cf1d34"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
