name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.11.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f15a0d2dcccf7f9008e9163ab33e325503ba1766d22315441fccfe8b0b7af80c"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
