name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.4.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c0633e4c5b0df074b70f39db6edd0f5b7cffb842bca73432550b50766bf141e"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
