name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.3.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5338b4dfce1d980e1b4d04a3e410f7c55999cc5a73dadba46861be2a32c0803a"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
