name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.7.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5ff5a75a9d309a38e1c51374f948afe6052bb28efb3d5907aec06a90fc19a72"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
