name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.9.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cd938f1ea4caa3c2a2b59ae07ef01780f5f2a370d25b567aa4efd95cf2951c8"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
