name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.3.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "134fb31bf1b0cd716f0bb7eadb8d7c854899d068e5e42578af2652fcee332743"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
