name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.8.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16f62c9b54c8520034643a650fff48d5f53f958be337084e7b34f9566101e5ca"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
