name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.13.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaafc0842fda3ac238a4030b49d26fb2dc6264fab755872ce73622976564e77e"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
