name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.6.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c08ce67ef7ea7805fe22e2202478c8222c7eed61ae88ab0865fe18a71e7ad48"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
