name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.12.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04ad03a76047b01fbb7de976dc7ae78247a906e778a899249086b3a123e59ad6"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
