name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "914c8b5dc8a0d27211ea534bcac78884219324908062be24770afb383956a773"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
