name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.13.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "091ae8e2c3dbece1e79ad4d8f5387fd60486a503303eb7afd8246ae59d2d2e8b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
