name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.16.7"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2b239d235224b0e9ed0ec7cdf20df0c4dbda2672a1149a924648750dc028a9a"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
