name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.11.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02d5f33ad07c5d2fa60d785ce4d55cf36762d3c1ceb761db0fa115f18102d7e0"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
