name = "Pepsi Dogs"
author = "Dan Porter"
version = "2.6.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3f5b0c289964abe9d0734f8fbb243df8b2c527ef196d69ae980f7c595a8c923"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
