name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.18.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "544cc06a61391a5f577545f8556b4189130dbe3a0994a8075a00172e5a1013e4"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
