name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.13.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5422c233305b073031f70219688e750befd7cf8a36abb2602d538ec387badea2"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
