name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.14.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4cf94d88788a52d0df858f5ac1556bf2d48df1faac6248599f53d8912604a46"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
