name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.15.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5242a35e52dafabdcc48aea92d7af64c5b340c9832d345bcd619013be3fe37c4"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
