name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.14.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3da6428d98301373edf7e5e08085859bedfadfece17a37170bcbacf6cff9b63"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
