name = "Pepsi Dogs"
author = "Dan Porter"
version = "2.12.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36689558f11fc9f2273955f37f27d8b2ac1cdb13a0c42f3ef112c3493d9dcd70"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
