name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.12.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7c5b67e8a248eb60d7d46f39d628b46da77dcb182dc63488a0f540f59a273fe"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
