name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.17.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc31d7d610702a2d3939f2c4bc4720230b4eac45db017029277bb40867eff2cb"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
