name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.12.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee648a490107002475cfe98844c6210b3b305a7a7fc1a3c24ca8cff929f9ba8b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
