name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.6.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a35c8cd9a7abba9bc649a4ca9ab5a8939b54a31cb821e29b573345751089f283"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
