name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.9.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29ac96e62c8e1e3782e12e5c6d7aa4f869dce0053c61129786aabb664e8e1b45"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
