name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.16.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbce1feccb2935269095b6449a396e70e86d4714da48f2664aa358467f0ec80e"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
