name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.9.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6deec2c2f90715575ffb8ab7d2b99f6a42ccd9f0fd986ac4188609cafdd9897a"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
