name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.19.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e4b61b906520f332d30cd5dbf109f3fa98b596e4b8ba807314b600f355ed600"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
