name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.3.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e62e9f48c3551bd9e16d5361870da46d20aa5108e07edfb79983697c6ebd79b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
