name = "Pepsi Dogs"
author = "Dan Porter"
version = "2.4.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "509d4becef8bd0e1b96b4b4501e0689407c968ccd35c7a3775394242717a8725"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
