name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.16.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51dfe2c79e5bac0aba4157c2b98aa968fe4a9982cb8410fd444c2a5bd99eeae0"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
