name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.11.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "339dc20a2429bc794e6c81a0f6677d866059d5697e0874380814f8e23be0db1b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
