name = "Pepsi Dogs"
author = "Dan Porter"
version = "2.12.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b73b5872def7e731442986cbf35b5e83befffa0bbb4829e5913fe2857031ac20"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
