name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.22.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "684d9352be381f8887a42f16941e97bf621ac43bbba5ad6da624ab80c309ac32"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
no-internal-hashes = true
