name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.23.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b81dfcd9d1e4b4b78592ac7b4893f810f78aea85e4f4242ef5b282ba6999e633"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
no-internal-hashes = true
