name = "Pepsi Dogs"
author = "Dan Porter"
version = "3.21.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40ebd7acb87efe63e68d7e18deb1f5cba5785203d91b05a7c4928da4621033fe"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
no-internal-hashes = true
