name = "Pepsi Dogs"
author = "Dan Porter"
version = "5.11.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
datapack-folder = "config/openloader/datapacks"
no-internal-hashes = true
