name = "Pepsi Dogs"
author = "Dan Porter"
version = "4.2.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "039655af0f4b3c305be2542c2ac932c11915107fad5750c1c6cfff3657542a54"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
no-internal-hashes = true
