name = "Pepsi Dogs"
author = "Dan Porter"
version = "4.2.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32b7a2c32164430f6d13de4b9b5762d266aa95de962d79c254908c0adeee5e5c"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
no-internal-hashes = true
