name = "Pepsi Dogs"
author = "Dan Porter"
version = "4.1.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c33e7eccf62cc84aafb328e65041cf1bcc68afcc468d9333abe5346989c0526"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
no-internal-hashes = true
