hash-format = "sha256"

[[files]]
file = "config/FabricProxy-Lite.toml"

[[files]]
file = "config/ticktools.toml"

[[files]]
file = "config/voicechat/voicechat-server.properties"

[[files]]
file = "mods/carpet.pw.toml"
metafile = true

[[files]]
file = "mods/damage-tilt.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabricproxy-lite.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/open-loader.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
metafile = true

[[files]]
file = "mods/ticktools.pw.toml"
metafile = true
