hash-format = "sha256"

[[files]]
file = "config/FabricProxy-Lite.toml"

[[files]]
file = "config/ticktools.toml"

[[files]]
file = "config/voicechat/voicechat-server.properties"

[[files]]
file = "mods/carpet.toml"
metafile = true

[[files]]
file = "mods/damage-tilt.toml"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
metafile = true

[[files]]
file = "mods/fabricproxy-lite.toml"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.toml"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
metafile = true

[[files]]
file = "mods/lithium.toml"
metafile = true

[[files]]
file = "mods/open-loader.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.toml"
metafile = true

[[files]]
file = "mods/starlight.toml"
metafile = true

[[files]]
file = "mods/ticktools.pw.toml"
metafile = true
