name = "Architectury API (Fabric)"
filename = "architectury-3.1.45.jar"
side = "both"

[option]
default = true
description = "An intermediary api aimed to ease developing multiplatform mods."
optional = false

[download]
url = "https://edge.forgecdn.net/files/3544/954/architectury-3.1.45.jar"
hash-format = "murmur2"
hash = "3836475077"

[update]
[update.curseforge]
file-id = 3544954
project-id = 419697
