name = "Architectury API (Fabric)"
filename = "architectury-3.2.51.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3562/469/architectury-3.2.51.jar"
hash-format = "murmur2"
hash = "2356609179"

[update]
[update.curseforge]
file-id = 3562469
project-id = 419697

[option]
optional = false
description = "An intermediary api aimed to ease developing multiplatform mods."
