name = "Architectury API (Fabric)"
filename = "architectury-3.4.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3587/337/architectury-3.4.9.jar"
hash-format = "murmur2"
hash = "3753628334"

[update]
[update.curseforge]
file-id = 3587337
project-id = 419697

[option]
optional = false
description = "An intermediary api aimed to ease developing multiplatform mods."
