name = "Architectury API (Fabric)"
filename = "architectury-3.2.60.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3577/741/architectury-3.2.60.jar"
hash-format = "murmur2"
hash = "60696494"

[update]
[update.curseforge]
file-id = 3577741
project-id = 419697

[option]
optional = false
description = "An intermediary api aimed to ease developing multiplatform mods."
