name = "Architectury API (Fabric)"
filename = "architectury-3.6.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3632/975/architectury-3.6.15.jar"
hash-format = "murmur2"
hash = "2863794581"

[update]
[update.curseforge]
file-id = 3632975
project-id = 419697

[option]
optional = false
description = "An intermediary api aimed to ease developing multiplatform mods."
