name = "Architectury API (Fabric)"
filename = "architectury-3.6.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3638/626/architectury-3.6.17.jar"
hash-format = "murmur2"
hash = "1058971165"

[update]
[update.curseforge]
file-id = 3638626
project-id = 419697

[option]
optional = false
description = "An intermediary api aimed to ease developing multiplatform mods."
