name = "Architectury API (Fabric)"
filename = "architectury-3.6.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/761/architectury-3.6.13.jar"
hash-format = "murmur2"
hash = "3874111088"

[update]
[update.curseforge]
file-id = 3631761
project-id = 419697

[option]
optional = false
description = "An intermediary api aimed to ease developing multiplatform mods."
