name = "Architectury API (Fabric)"
filename = "architectury-3.3.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3582/323/architectury-3.3.5.jar"
hash-format = "murmur2"
hash = "1435842436"

[update]
[update.curseforge]
file-id = 3582323
project-id = 419697

[option]
optional = false
description = "An intermediary api aimed to ease developing multiplatform mods."
