name = "Architectury API (Fabric)"
filename = "architectury-3.6.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3636/539/architectury-3.6.16.jar"
hash-format = "murmur2"
hash = "3669130180"

[update]
[update.curseforge]
file-id = 3636539
project-id = 419697

[option]
optional = false
description = "An intermediary api aimed to ease developing multiplatform mods."
