name = "Architectury API (Fabric)"
filename = "architectury-3.3.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3586/574/architectury-3.3.7.jar"
hash-format = "murmur2"
hash = "57975785"

[update]
[update.curseforge]
file-id = 3586574
project-id = 419697

[option]
optional = false
description = "An intermediary api aimed to ease developing multiplatform mods."
