name = "Architectury API (Fabric)"
filename = "architectury-3.2.47.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3554/993/architectury-3.2.47.jar"
hash-format = "murmur2"
hash = "3145725562"

[update]
[update.curseforge]
file-id = 3554993
project-id = 419697

[option]
optional = false
description = "An intermediary api aimed to ease developing multiplatform mods."
