name = "Better Mount HUD"
filename = "bettermounthud-1.1.2.jar"
side = "client"

[option]
default = false
description = "Improves mount HUD, adding your hunger and restoring XP bar when not jumping."
optional = true

[download]
url = "https://edge.forgecdn.net/files/3380/384/bettermounthud-1.1.2.jar"
hash-format = "murmur2"
hash = "1872359493"

[update]
[update.curseforge]
file-id = 3380384
project-id = 475358
