name = "Better Third Person"
filename = "BetterThirdPerson-Fabric-1.18-1.6.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3581/979/BetterThirdPerson-Fabric-1.18-1.6.0.jar"
hash-format = "murmur2"
hash = "1658513908"

[update]
[update.curseforge]
file-id = 3581979
project-id = 435044

[option]
optional = true
description = "Adds independent rotation of the camera from a third person view."
default = true
