name = "Better Mount HUD"
filename = "bettermounthud-1.1.3.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3556/489/bettermounthud-1.1.3.jar"
hash-format = "murmur2"
hash = "1229323412"

[update]
[update.curseforge]
file-id = 3556489
project-id = 475358

[option]
optional = true
description = "Improves mount HUD, adding your hunger and restoring XP bar when not jumping."
default = true
