name = "Better Third Person"
filename = "BetterThirdPerson-Fabric-1.18-1.5.4.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3541/976/BetterThirdPerson-Fabric-1.18-1.5.4.jar"
hash-format = "murmur2"
hash = "1311710536"

[update]
[update.curseforge]
file-id = 3541976
project-id = 435044

[option]
optional = true
description = "Adds independent rotation of the camera from a third person view."
default = true
