name = "Better Ping Display [Fabric]"
filename = "BetterPingDisplay-Fabric-1.18.1-1.1.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3565/287/BetterPingDisplay-Fabric-1.18.1-1.1.1.jar"
hash-format = "murmur2"
hash = "1407778813"

[update]
[update.curseforge]
file-id = 3565287
project-id = 406343
