name = "Concurrent Chunk Management Engine (Fabric)"
filename = "c2me-fabric-mc1.18.1-0.2.0+alpha.6.55-all.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3654/495/c2me-fabric-mc1.18.1-0.2.0+alpha.6.55-all.jar"
hash-format = "sha1"
hash = "dcc477b1b2f92d5ccad62435657aa985ad8bd8ce"

[update]
[update.curseforge]
file-id = 3654495
project-id = 533097
