name = "Carpet"
filename = "fabric-carpet-1.18-1.4.56+v211130.jar"
side = "both"

[option]
default = true
description = "Carpet mod."
optional = false

[download]
url = "https://edge.forgecdn.net/files/3542/18/fabric-carpet-1.18-1.4.56+v211130.jar"
hash-format = "murmur2"
hash = "3541337216"

[update]
[update.curseforge]
file-id = 3542018
project-id = 349239
