name = "Clear Despawn [Fabric]"
filename = "ClearDespawn-fabric-1.18.1-1.1.6.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3615/727/ClearDespawn-fabric-1.18.1-1.1.6.jar"
hash-format = "murmur2"
hash = "3720824713"

[update]
[update.curseforge]
file-id = 3615727
project-id = 308793

[option]
optional = true
description = "Makes dropped items flash when they're about to de-spawn."
default = true
