name = "Cloth Config API (Fabric)"
filename = "cloth-config-6.0.45-fabric.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3546/622/cloth-config-6.0.45-fabric.jar"
hash-format = "murmur2"
hash = "4158055047"

[update]
[update.curseforge]
file-id = 3546622
project-id = 319057

[option]
description = "Config Screen API."
