name = "Cloth Config API (Fabric)"
filename = "cloth-config-6.1.48-fabric.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3559/638/cloth-config-6.1.48-fabric.jar"
hash-format = "murmur2"
hash = "2178376205"

[update]
[update.curseforge]
file-id = 3559638
project-id = 319057

[option]
optional = false
description = "Config Screen API."
