name = "Cloth Config API (Fabric)"
filename = "cloth-config-6.2.57-fabric.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3641/132/cloth-config-6.2.57-fabric.jar"
hash-format = "murmur2"
hash = "285374830"

[update]
[update.curseforge]
file-id = 3641132
project-id = 319057

[option]
optional = false
description = "Config Screen API."
