name = "EasierCrafting"
filename = "easiercrafting-1.18.1-fabric0.45.0-1.7.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3606/823/easiercrafting-1.18.1-fabric0.45.0-1.7.jar"
hash-format = "murmur2"
hash = "2808903388"

[update]
[update.curseforge]
file-id = 3606823
project-id = 265956

[option]
optional = true
description = "Quick crafting in a sidebar menu."
