name = "EasierVillagerTrading"
filename = "easiervillagertrading-1.18-fabric0.43.1-1.5.4.jar"
side = "client"

[option]
default = true
description = "Villager trades are insta-click."
optional = true

[download]
url = "https://edge.forgecdn.net/files/3543/431/easiervillagertrading-1.18-fabric0.43.1-1.5.4.jar"
hash-format = "murmur2"
hash = "1082131574"

[update]
[update.curseforge]
file-id = 3543431
project-id = 261605
