name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-Fabric-1.18.1-9.0.12.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3618/460/EnchantmentDescriptions-Fabric-1.18.1-9.0.12.jar"
hash-format = "murmur2"
hash = "4187168283"

[update]
[update.curseforge]
file-id = 3618460
project-id = 250419

[option]
optional = true
description = "Adds descriptions of enchantments to the tool tip of enchanted books."
default = true
