name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-Fabric-1.18.1-9.0.8.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3595/253/EnchantmentDescriptions-Fabric-1.18.1-9.0.8.jar"
hash-format = "murmur2"
hash = "1358562159"

[update]
[update.curseforge]
file-id = 3595253
project-id = 250419

[option]
optional = true
description = "Adds descriptions of enchantments to the tool tip of enchanted books."
default = true
