name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-Fabric-1.18.1-9.0.4.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3576/548/EnchantmentDescriptions-Fabric-1.18.1-9.0.4.jar"
hash-format = "murmur2"
hash = "774274084"

[update]
[update.curseforge]
file-id = 3576548
project-id = 250419

[option]
optional = true
description = "Adds descriptions of enchantments to the tool tip of enchanted books."
default = true
