name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-Fabric-1.18.1-9.0.9.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3601/864/EnchantmentDescriptions-Fabric-1.18.1-9.0.9.jar"
hash-format = "murmur2"
hash = "988435619"

[update]
[update.curseforge]
file-id = 3601864
project-id = 250419

[option]
optional = true
description = "Adds descriptions of enchantments to the tool tip of enchanted books."
default = true
