name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-Fabric-1.18.1-9.0.7.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3586/39/EnchantmentDescriptions-Fabric-1.18.1-9.0.7.jar"
hash-format = "murmur2"
hash = "3957928408"

[update]
[update.curseforge]
file-id = 3586039
project-id = 250419

[option]
optional = true
description = "Adds descriptions of enchantments to the tool tip of enchanted books."
default = true
