name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-Fabric-1.18.1-9.0.5.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3582/625/EnchantmentDescriptions-Fabric-1.18.1-9.0.5.jar"
hash-format = "murmur2"
hash = "4131898747"

[update]
[update.curseforge]
file-id = 3582625
project-id = 250419

[option]
optional = true
description = "Adds descriptions of enchantments to the tool tip of enchanted books."
default = true
