name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-Fabric-1.18.1-9.0.10.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3611/737/EnchantmentDescriptions-Fabric-1.18.1-9.0.10.jar"
hash-format = "murmur2"
hash = "2604486720"

[update]
[update.curseforge]
file-id = 3611737
project-id = 250419

[option]
optional = true
description = "Adds descriptions of enchantments to the tool tip of enchanted books."
default = true
