name = "Fabric API"
filename = "fabric-api-0.45.0+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3577/46/fabric-api-0.45.0+1.18.jar"
hash-format = "murmur2"
hash = "3382045089"

[update]
[update.curseforge]
file-id = 3577046
project-id = 306612

[option]
optional = false
description = "Fabric API."
