name = "Fabric API"
filename = "fabric-api-0.46.1+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3609/610/fabric-api-0.46.1+1.18.jar"
hash-format = "murmur2"
hash = "2436139110"

[update]
[update.curseforge]
file-id = 3609610
project-id = 306612

[option]
optional = false
description = "Fabric API."
