name = "Fabric API"
filename = "fabric-api-0.45.2+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3595/229/fabric-api-0.45.2+1.18.jar"
hash-format = "murmur2"
hash = "2626514222"

[update]
[update.curseforge]
file-id = 3595229
project-id = 306612

[option]
optional = false
description = "Fabric API."
