name = "Fabric API"
filename = "fabric-api-0.46.0+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3605/891/fabric-api-0.46.0+1.18.jar"
hash-format = "murmur2"
hash = "4085079180"

[update]
[update.curseforge]
file-id = 3605891
project-id = 306612

[option]
optional = false
description = "Fabric API."
