name = "Fabric API"
filename = "fabric-api-0.46.3+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/946/fabric-api-0.46.3+1.18.jar"
hash-format = "murmur2"
hash = "2573151562"

[update]
[update.curseforge]
file-id = 3630946
project-id = 306612

[option]
optional = false
description = "Fabric API."
