name = "Fabric API"
filename = "fabric-api-0.46.2+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/749/fabric-api-0.46.2+1.18.jar"
hash-format = "murmur2"
hash = "2320157107"

[update]
[update.curseforge]
file-id = 3613749
project-id = 306612

[option]
optional = false
description = "Fabric API."
