name = "Fabric API"
filename = "fabric-api-0.45.1+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3591/502/fabric-api-0.45.1+1.18.jar"
hash-format = "murmur2"
hash = "1772098389"

[update]
[update.curseforge]
file-id = 3591502
project-id = 306612

[option]
optional = false
description = "Fabric API."
