name = "Fabric API"
filename = "fabric-api-0.44.0+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3546/679/fabric-api-0.44.0+1.18.jar"
hash-format = "murmur2"
hash = "3738481999"

[update]
[update.curseforge]
file-id = 3546679
project-id = 306612
