name = "FerriteCore (Fabric)"
filename = "ferritecore-4.0.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3550/48/ferritecore-4.0.0-fabric.jar"
hash-format = "murmur2"
hash = "4229292133"

[update]
[update.curseforge]
file-id = 3550048
project-id = 459857
