name = "FerriteCore"
filename = "ferritecore-4.0.0-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/uXXizFIs/versions/4.0.0/ferritecore-4.0.0-fabric.jar"
hash-format = "sha512"
hash = "2e5e5d03e21190bf1ebe5889a6387f001cfe8e7d6f90bff6d5f0d4fdfca1bd445c6ee1e5ec64207ba19df35364917b4f8e3a769cc5391ee77dbf81d579cd1e05"

[update]
[update.modrinth]
mod-id = "uXXizFIs"
version = "1FrNtQTK"

[option]
description = "Reduces the memory usage of Minecraft in a few different ways."
