name = "FerriteCore (Fabric)"
filename = "ferritecore-4.1.2-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/642/ferritecore-4.1.2-fabric.jar"
hash-format = "sha1"
hash = "11d973fe8601658fade9f9981f568efb4b8a5dce"

[update]
[update.curseforge]
file-id = 3652642
project-id = 459857
