name = "Giselbaer's Durability Viewer"
filename = "durabilityviewer-1.18-fabric0.43.1-1.10.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/427/durabilityviewer-1.18-fabric0.43.1-1.10.2.jar"
hash-format = "murmur2"
hash = "3146442372"

[update]
[update.curseforge]
file-id = 3543427
project-id = 262146
