name = "Indium"
filename = "indium-1.0.2-alpha2+mc1.18.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/Orvt0mRa/versions/1.0.2-alpha2+mc1.18.1/indium-1.0.2-alpha2+mc1.18.1.jar"
hash-format = "sha512"
hash = "efdc21f516aaf78c28745db83172126e6685ae63b2ae273eb3df2a7d49ef7197d2e670c10cd20cbdb388cf6793821f72191350e3f0dc8235f4fb700709186dfe"

[update]
[update.modrinth]
mod-id = "Orvt0mRa"
version = "CVUGSVU0"

[option]
optional = true
description = "Needed for litematica, Fabric Rendering API support for Sodium."
