name = "Indium"
filename = "indium-1.0.2-alpha2+mc1.18.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3606/937/indium-1.0.2-alpha2+mc1.18.1.jar"
hash-format = "murmur2"
hash = "2698217568"

[update]
[update.curseforge]
file-id = 3606937
project-id = 459496

[option]
optional = true
description = "Needed for litematica, Fabric Rendering API support for Sodium."
