name = "Iris Shaders"
filename = "iris-mc1.18-1.1.3.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3542/382/iris-mc1.18-1.1.3.jar"
hash-format = "murmur2"
hash = "4029896349"

[update]
[update.curseforge]
file-id = 3542382
project-id = 455508

[option]
description = "Optifine shader support for Sodium."
