name = "Iris Shaders"
filename = "iris-mc1.18.1-1.1.4.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3596/182/iris-mc1.18.1-1.1.4.jar"
hash-format = "murmur2"
hash = "3265639627"

[update]
[update.curseforge]
file-id = 3596182
project-id = 455508

[option]
optional = false
description = "Optifine shader support for Sodium."
