name = "Iris Shaders"
filename = "iris-mc1.18.1-1.1.5.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3605/379/iris-mc1.18.1-1.1.5.jar"
hash-format = "murmur2"
hash = "3886317776"

[update]
[update.curseforge]
file-id = 3605379
project-id = 455508

[option]
optional = false
description = "Optifine shader support for Sodium."
