name = "Krypton"
filename = "krypton-0.1.5.jar"
side = "both"

[option]
default = true
description = "Optomizes the Minecraft networking stack."
optional = false

[download]
url = "https://edge.forgecdn.net/files/3542/839/krypton-0.1.5.jar"
hash-format = "murmur2"
hash = "2122985240"

[update]
[update.curseforge]
file-id = 3542839
project-id = 428912
