name = "Ledger"
filename = "ledger-1.2.0.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3541/799/ledger-1.2.0.jar"
hash-format = "murmur2"
hash = "1373449325"

[update]
[update.curseforge]
file-id = 3541799
project-id = 491137

[option]
description = "server-side fabric logging mod"
