name = "Litematica"
filename = "litematica-fabric-1.18.0-0.9.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3580/242/litematica-fabric-1.18.0-0.9.0.jar"
hash-format = "murmur2"
hash = "640595593"

[update]
[update.curseforge]
file-id = 3580242
project-id = 308892

[option]
optional = true
description = "Build schematic mod."
