name = "Lithium (Fabric)"
filename = "lithium-fabric-mc1.18.1-0.7.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/908/lithium-fabric-mc1.18.1-0.7.7.jar"
hash-format = "murmur2"
hash = "2688647578"

[update]
[update.curseforge]
file-id = 3590908
project-id = 360438

[option]
optional = false
description = "General-purpose optimization mod."
