name = "Lithium (Fabric)"
filename = "lithium-fabric-mc1.18.1-0.7.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3659/182/lithium-fabric-mc1.18.1-0.7.8.jar"
hash-format = "sha1"
hash = "8b7cd216fee54b9acc261005cae5acbc856b1933"

[update]
[update.curseforge]
file-id = 3659182
project-id = 360438

[option]
optional = false
description = "General-purpose optimization mod."
