name = "MaLiLib"
filename = "malilib-fabric-1.18.0-0.10.0-dev.26.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3544/210/malilib-fabric-1.18.0-0.10.0-dev.26.jar"
hash-format = "murmur2"
hash = "4277400873"

[update]
[update.curseforge]
file-id = 3544210
project-id = 303119
