name = "MaLiLib"
filename = "malilib-fabric-1.18.1-0.11.6.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3630/909/malilib-fabric-1.18.1-0.11.6.jar"
hash-format = "murmur2"
hash = "918701965"

[update]
[update.curseforge]
file-id = 3630909
project-id = 303119

[option]
optional = false
description = "Library for masa's client-side mods."
