name = "Mod Menu"
filename = "modmenu-3.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3479/754/modmenu-3.0.0.jar"
hash-format = "murmur2"
hash = "2387229544"

[update]
[update.curseforge]
file-id = 3479754
project-id = 308702
