name = "multiconnect"
filename = "multiconnect-1.5.3.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3556/102/multiconnect-1.5.3.jar"
hash-format = "murmur2"
hash = "1214764654"

[update]
[update.curseforge]
file-id = 3556102
project-id = 336018

[option]
optional = true
description = "Support connecting to older Minecraft servers."
