name = "multiconnect"
filename = "multiconnect-1.5.7.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3574/173/multiconnect-1.5.7.jar"
hash-format = "murmur2"
hash = "2567658737"

[update]
[update.curseforge]
file-id = 3574173
project-id = 336018

[option]
optional = true
description = "Support connecting to older Minecraft servers."
