name = "No Fade"
filename = "nofade-1.18-2.0.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3550/935/nofade-1.18-2.0.1.jar"
hash-format = "murmur2"
hash = "4017265390"

[update]
[update.curseforge]
file-id = 3550935
project-id = 452768

[option]
description = "Removes the transition fade within the menus."
