name = "Not Enough Crashes (Fabric)"
filename = "notenoughcrashes-4.1.3+1.18-fabric.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3545/827/notenoughcrashes-4.1.3+1.18-fabric.jar"
hash-format = "murmur2"
hash = "262039561"

[update]
[update.curseforge]
file-id = 3545827
project-id = 353890

[option]
description = "Improves crashes in Minecraft."
