name = "Not Enough Crashes (Fabric)"
filename = "notenoughcrashes-4.1.3+1.18.1-fabric.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3578/934/notenoughcrashes-4.1.3+1.18.1-fabric.jar"
hash-format = "murmur2"
hash = "1758673091"

[update]
[update.curseforge]
file-id = 3578934
project-id = 353890

[option]
optional = false
description = "Improves crashes in Minecraft."
