name = "Open Loader"
filename = "OpenLoader-Fabric-1.18.1-11.0.2.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3583/806/OpenLoader-Fabric-1.18.1-11.0.2.jar"
hash-format = "murmur2"
hash = "2531051044"

[update]
[update.curseforge]
file-id = 3583806
project-id = 354339
