name = "Open Loader"
filename = "OpenLoader-Fabric-1.18.1-11.0.3.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3586/547/OpenLoader-Fabric-1.18.1-11.0.3.jar"
hash-format = "murmur2"
hash = "4169323390"

[update]
[update.curseforge]
file-id = 3586547
project-id = 354339
