name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.1-2.2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3601/151/voicechat-fabric-1.18.1-2.2.5.jar"
hash-format = "murmur2"
hash = "4182984025"

[update]
[update.curseforge]
file-id = 3601151
project-id = 416089

[option]
optional = false
description = "In-game proximity voice chat."
