name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.1-2.2.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/228/voicechat-fabric-1.18.1-2.2.9.jar"
hash-format = "murmur2"
hash = "58042817"

[update]
[update.curseforge]
file-id = 3613228
project-id = 416089

[option]
optional = false
description = "In-game proximity voice chat."
