name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.1-2.2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3598/200/voicechat-fabric-1.18.1-2.2.4.jar"
hash-format = "murmur2"
hash = "4152017334"

[update]
[update.curseforge]
file-id = 3598200
project-id = 416089

[option]
optional = false
description = "In-game proximity voice chat."
