name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.1-2.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3594/988/voicechat-fabric-1.18.1-2.2.2.jar"
hash-format = "murmur2"
hash = "143668687"

[update]
[update.curseforge]
file-id = 3594988
project-id = 416089

[option]
optional = false
description = "In-game proximity voice chat."
