name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.1-2.2.21.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3638/505/voicechat-fabric-1.18.1-2.2.21.jar"
hash-format = "murmur2"
hash = "2597730445"

[update]
[update.curseforge]
file-id = 3638505
project-id = 416089

[option]
optional = false
description = "In-game proximity voice chat."
