name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.1-2.1.28.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3571/844/voicechat-fabric-1.18.1-2.1.28.jar"
hash-format = "murmur2"
hash = "526783905"

[update]
[update.curseforge]
file-id = 3571844
project-id = 416089

[option]
optional = false
description = "In-game proximity voice chat."
