name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.1-2.2.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/542/voicechat-fabric-1.18.1-2.2.10.jar"
hash-format = "murmur2"
hash = "779372851"

[update]
[update.curseforge]
file-id = 3613542
project-id = 416089

[option]
optional = false
description = "In-game proximity voice chat."
