name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.1-2.2.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3625/663/voicechat-fabric-1.18.1-2.2.14.jar"
hash-format = "murmur2"
hash = "1900098469"

[update]
[update.curseforge]
file-id = 3625663
project-id = 416089

[option]
optional = false
description = "In-game proximity voice chat."
