name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.1-2.2.19.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3635/283/voicechat-fabric-1.18.1-2.2.19.jar"
hash-format = "murmur2"
hash = "1545504860"

[update]
[update.curseforge]
file-id = 3635283
project-id = 416089

[option]
optional = false
description = "In-game proximity voice chat."
