name = "Sodium"
filename = "sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3542/74/sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar"
hash-format = "murmur2"
hash = "2315531696"

[update]
[update.curseforge]
file-id = 3542074
project-id = 394468

[option]
description = "Rendering engine replacement."
