name = "Starlight (Fabric)"
filename = "starlight-1.0.1+fabric.0583973.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/857/starlight-1.0.1+fabric.0583973.jar"
hash-format = "murmur2"
hash = "1327091267"

[update]
[update.curseforge]
file-id = 3599857
project-id = 521783

[option]
description = "Rewrites the light engine to fix lighting performance and lighting errors."
