name = "Tweakeroo"
filename = "tweakeroo-fabric-1.18.1-0.12.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3619/955/tweakeroo-fabric-1.18.1-0.12.1.jar"
hash-format = "murmur2"
hash = "1670516680"

[update]
[update.curseforge]
file-id = 3619955
project-id = 297344

[option]
optional = true
description = "Adds a bunch of various tweaks, including auto-clicker, freecam, tool change, etc."
