name = "Tweakeroo"
filename = "tweakeroo-fabric-1.18.1-0.12.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3630/905/tweakeroo-fabric-1.18.1-0.12.2.jar"
hash-format = "murmur2"
hash = "665110247"

[update]
[update.curseforge]
file-id = 3630905
project-id = 297344

[option]
optional = true
description = "Adds a bunch of various tweaks, including auto-clicker, freecam, tool change, etc."
