name = "WorldEdit"
filename = "worldedit-mod-7.2.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3559/499/worldedit-mod-7.2.8.jar"
hash-format = "murmur2"
hash = "626940980"

[update]
[update.curseforge]
file-id = 3559499
project-id = 225608

[option]
optional = true
description = "For chunk resetting and other maintenance tasks."
default = false
