name = "WorldEdit"
filename = "worldedit-mod-7.2.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/606/worldedit-mod-7.2.9.jar"
hash-format = "murmur2"
hash = "3850091270"

[update]
[update.curseforge]
file-id = 3631606
project-id = 225608

[option]
optional = true
description = "For chunk resetting and other maintenance tasks."
