name: packwiz-ci

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.7'
      - name: Set up packwiz
        run: go install github.com/packwiz/packwiz@latest
      - name: Packwiz refresh build
        run: for pack in $(find . -type f -name 'pack.toml' -exec dirname "{}" \;); do (echo "Running packwiz refresh --build on '${pack}'" && cd ${pack} && packwiz refresh --build); done
